# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b924d4a226a1a50c1103585c35966b5f7cff23540127d1124956adc31873f75973a2b71793e78876da012c8563ce424fe909dfb3376b10e908a3508911f79843

test:
  secret_key_base: 06c6af4d584727f4a9c92ab002de17c3bcc9abec5aa92d13f04ae976aae8f6847204cae3bba463c0d1dc2aeddada1e06a1c309cb1b689874e909986fc5227e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
